spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_one?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: 12345
      initialSize : 5
      minIdle : 5
      maxActive : 20
      # 配置获取连接等待超时的时间
      maxWait : 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis : 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis : 300000
      validationQuery : SELECT 1
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements : true
      maxPoolPreparedStatementPerConnectionSize : 20
      #druid配置
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters : stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties : druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat : true
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效